export const API_ROUTES = {
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    google: '/auth/callback',
    wsToken: '/auth/ws-token',
    forgotPassword: '/auth/password-reset/request',
    resetPassword: '/auth/password-reset/confirm',
  },
  notifications: {
    list: '/notifications',
    unreadCount: '/notifications/unread-count',
    markRead: (id: string) => `/notifications/${id}/read`,
    markAllRead: '/notifications/read-all',
    preferences: '/notifications/preferences',
  },
  users: {
    me: '/users/me',
    avatar: '/users/me/avatar',
    language: '/users/me/language',
    physicalData: '/users/me/physical-data',
    search: '/users',
    publicProfile: (id: string) => `/users/${id}`,
    sessionHistory: (id: string) => `/users/${id}/sessions`,
    deleteAccount: '/users/me',
  },
  exercises: {
    list: '/exercises',
    detail: (id: string) => `/exercises/${id}`,
    create: '/exercises',
    update: (id: string) => `/exercises/${id}`,
    delete: (id: string) => `/exercises/${id}`,
  },
  workoutPlans: {
    list: '/workout-plans',
    active: '/workout-plans/active',
    detail: (id: string) => `/workout-plans/${id}`,
    activate: (id: string) => `/workout-plans/${id}/activate`,
    duplicate: (id: string) => `/workout-plans/${id}/duplicate`,
    copyDay: (id: string, dayOfWeek: string) => `/workout-plans/${id}/days/${dayOfWeek}/copy`,
    goals: (id: string) => `/workout-plans/${id}/goals`,
    autoUpdate: (id: string) => `/workout-plans/${id}/auto-update`,
  },
  sessions: {
    start: '/sessions',
    active: '/sessions/active',
    cancel: '/sessions/active',
    detail: (id: string) => `/sessions/${id}`,
    logSet: (id: string) => `/sessions/${id}/sets`,
    modifyExercise: (id: string, exerciseId: string) => `/sessions/${id}/exercises/${exerciseId}`,
    replaceExercise: (id: string, exerciseId: string) => `/sessions/${id}/exercises/${exerciseId}`,
    addExercises: (id: string) => `/sessions/${id}/exercises`,
    finish: (id: string) => `/sessions/${id}/finish`,
    sync: '/sessions/sync',
    history: '/sessions',
  },
  stats: {
    exerciseHistory: (exerciseId: string) => `/stats/exercises/${exerciseId}/history`,
    exercisePrs: (exerciseId: string) => `/stats/exercises/${exerciseId}/prs`,
    exerciseVolume: (exerciseId: string) => `/stats/exercises/${exerciseId}/volume`,
    volume: '/stats/volume',
    muscles: '/stats/muscles',
  },
  social: {
    follow: (userId: string) => `/social/follow/${userId}`,
    unfollow: (userId: string) => `/social/follow/${userId}`,
    followers: (userId: string) => `/social/followers/${userId}`,
    following: (userId: string) => `/social/following/${userId}`,
    followRequests: {
      pending: '/social/follow-requests/pending',
      approve: (userId: string) => `/social/follow-request/${userId}/approve`,
      reject: (userId: string) => `/social/follow-request/${userId}/reject`,
      cancel: (userId: string) => `/social/follow-request/${userId}/cancel`,
    },
  },
  feed: {
    list: '/feed',
    create: '/feed/posts',
    sharePlan: '/feed/plans',
    copySharedPlan: (postId: string) => `/feed/posts/${postId}/copy`,
    post: (postId: string) => `/feed/posts/${postId}`,
    reactions: (postId: string) => `/feed/posts/${postId}/reactions`,
    removeReaction: (postId: string) => `/feed/posts/${postId}/reactions`,
    comments: (postId: string) => `/feed/posts/${postId}/comments`,
    addReply: (postId: string, commentId: string) => `/feed/posts/${postId}/comments/${commentId}/replies`,
  },
  admin: {
    users: '/admin/users',
    paymentLogs: '/admin/payment-logs',
    setUserStatus: (id: string) => `/admin/users/${id}/status`,
    setUserRole: (id: string) => `/admin/users/${id}/role`,
    giftMembership: (id: string) => `/admin/users/${id}/membership/gift`,
    revokeMembership: (id: string) => `/admin/users/${id}/membership/revoke`,
    exercises: '/admin/exercises',
    exerciseDetail: (id: string) => `/admin/exercises/${id}`,
    monitoring: {
      users: '/admin/monitoring/users',
      subscriptions: '/admin/monitoring/subscriptions',
      ai: '/admin/monitoring/ai',
      errors: '/admin/monitoring/errors',
    },
  },
  ranks: {
    muscles: '/ranks/muscles',
    leaderboard: '/ranks/leaderboard',
    exercise: (exerciseId: string) => `/ranks/exercises/${exerciseId}`,
  },
  recovery: {
    muscles: '/recovery/muscles',
  },
  subscriptions: {
    checkout: '/subscriptions/checkout',
    me: '/subscriptions/me',
    autoRenew: '/subscriptions/auto-renew',
  },
  streaks: {
    me: '/streaks',
  },
  titles: {
    my: '/titles/my',
    setActive: '/users/me/active-title',
  },
  terms: {
    adminList: '/terms/admin',
    create: '/terms',
    update: (id: string) => `/terms/${id}`,
    delete: (id: string) => `/terms/${id}`,
  },
  ai: {
    generatePlan: '/ai/plans/generate',
    profiles: '/ai/plans/profiles',
    analyzeProgression: '/ai/progression/analyze',
    confirmProgression: '/ai/progression/confirm',
    currentWeekProgression: '/ai/progression/current-week',
    suggestReplacement: (planId: string, exerciseId: string) =>
      `/ai/plans/${planId}/exercises/${exerciseId}/suggest-replacement`,
    confirmReplacement: (planId: string, exerciseId: string) =>
      `/ai/plans/${planId}/exercises/${exerciseId}/confirm-replacement`,
  },
  export: {
    sessionPdf: (id: string) => `/export/sessions/${id}/pdf`,
    sessionCsv: (id: string) => `/export/sessions/${id}/csv`,
    historyPdf: '/export/history/pdf',
    historyCsv: '/export/history/csv',
  },
} as const;
